#!/usr/bin/env node
// Rebuilds src/graphql/schema.graphql from the pinned streamarr-server commit: every .graphqls
// file under the schema directory, concatenated in stable name order behind a provenance header.
// The pin is exact — bumping it is a deliberate, reviewed change.
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pin = JSON.parse(await readFile(join(root, 'src/graphql/schema.pin.json'), 'utf8'))

const treeUrl = `https://api.github.com/repos/${pin.repository}/git/trees/${pin.commit}?recursive=1`
const tree = await fetchJson(treeUrl)
if (tree.truncated) {
  throw new Error(`Tree listing for ${pin.repository}@${pin.commit} was truncated; the schema would be incomplete`)
}
const files = tree.tree
  .filter(
    (entry) =>
      entry.type === 'blob' &&
      entry.path.startsWith(`${pin.schemaDirectory}/`) &&
      entry.path.endsWith('.graphqls'),
  )
  .map((entry) => entry.path)
  .sort()

if (files.length === 0) {
  throw new Error(`No schema files found under ${pin.schemaDirectory} at ${pin.commit}`)
}

const parts = []
for (const path of files) {
  const raw = await fetchText(
    `https://raw.githubusercontent.com/${pin.repository}/${pin.commit}/${path}`,
  )
  parts.push(`# --- ${path.split('/').pop()} ---\n${raw.trimEnd()}\n`)
}

const header = [
  '# Generated by scripts/pull-schema.mjs — do not edit.',
  `# Source: ${pin.repository}@${pin.commit}`,
  `# Files: ${files.length} under ${pin.schemaDirectory}, concatenated in name order.`,
  '',
].join('\n')

await writeFile(join(root, 'src/graphql/schema.graphql'), header + '\n' + parts.join('\n'))
console.log(`Wrote src/graphql/schema.graphql from ${files.length} files at ${pin.commit}`)

async function fetchJson(url) {
  const response = await fetch(url, { headers: githubHeaders() })
  if (!response.ok) throw new Error(`${url} answered ${response.status}`)
  return response.json()
}

async function fetchText(url) {
  const response = await fetch(url, { headers: githubHeaders() })
  if (!response.ok) throw new Error(`${url} answered ${response.status}`)
  return response.text()
}

function githubHeaders() {
  return process.env.GITHUB_TOKEN
    ? { authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
    : {}
}
