/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLinkRouteImport } from './routes/_authenticated/link'
import { Route as AuthenticatedSelectRouteImport } from './routes/_authenticated/select'
import { Route as AuthenticatedSharingRouteImport } from './routes/_authenticated/sharing'
import { Route as AuthenticatedPlayMediaFileIdRouteImport } from './routes/_authenticated/play.$mediaFileId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkRoute = AuthenticatedLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelectRoute = AuthenticatedSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSharingRoute = AuthenticatedSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayMediaFileIdRoute =
  AuthenticatedPlayMediaFileIdRouteImport.update({
    id: '/play/$mediaFileId',
    path: '/play/$mediaFileId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/link': typeof AuthenticatedLinkRoute
  '/select': typeof AuthenticatedSelectRoute
  '/sharing': typeof AuthenticatedSharingRoute
  '/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/link': typeof AuthenticatedLinkRoute
  '/select': typeof AuthenticatedSelectRoute
  '/sharing': typeof AuthenticatedSharingRoute
  '/': typeof AuthenticatedIndexRoute
  '/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/_authenticated/link': typeof AuthenticatedLinkRoute
  '/_authenticated/select': typeof AuthenticatedSelectRoute
  '/_authenticated/sharing': typeof AuthenticatedSharingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/login'
    | '/reset'
    | '/setup'
    | '/link'
    | '/select'
    | '/sharing'
    | '/play/$mediaFileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/login'
    | '/reset'
    | '/setup'
    | '/link'
    | '/select'
    | '/sharing'
    | '/'
    | '/play/$mediaFileId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/invite'
    | '/login'
    | '/reset'
    | '/setup'
    | '/_authenticated/link'
    | '/_authenticated/select'
    | '/_authenticated/sharing'
    | '/_authenticated/'
    | '/_authenticated/play/$mediaFileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/link': {
      id: '/_authenticated/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AuthenticatedLinkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/select': {
      id: '/_authenticated/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof AuthenticatedSelectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sharing': {
      id: '/_authenticated/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof AuthenticatedSharingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/$mediaFileId': {
      id: '/_authenticated/play/$mediaFileId'
      path: '/play/$mediaFileId'
      fullPath: '/play/$mediaFileId'
      preLoaderRoute: typeof AuthenticatedPlayMediaFileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLinkRoute: typeof AuthenticatedLinkRoute
  AuthenticatedSelectRoute: typeof AuthenticatedSelectRoute
  AuthenticatedSharingRoute: typeof AuthenticatedSharingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlayMediaFileIdRoute: typeof AuthenticatedPlayMediaFileIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLinkRoute: AuthenticatedLinkRoute,
  AuthenticatedSelectRoute: AuthenticatedSelectRoute,
  AuthenticatedSharingRoute: AuthenticatedSharingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlayMediaFileIdRoute: AuthenticatedPlayMediaFileIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
