/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSelectRouteImport } from './routes/_authenticated/select'
import { Route as AuthenticatedLinkRouteImport } from './routes/_authenticated/link'
import { Route as AuthenticatedPlayMediaFileIdRouteImport } from './routes/_authenticated/play.$mediaFileId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelectRoute = AuthenticatedSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkRoute = AuthenticatedLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayMediaFileIdRoute =
  AuthenticatedPlayMediaFileIdRouteImport.update({
    id: '/play/$mediaFileId',
    path: '/play/$mediaFileId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/link': typeof AuthenticatedLinkRoute
  '/select': typeof AuthenticatedSelectRoute
  '/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/link': typeof AuthenticatedLinkRoute
  '/select': typeof AuthenticatedSelectRoute
  '/': typeof AuthenticatedIndexRoute
  '/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/link': typeof AuthenticatedLinkRoute
  '/_authenticated/select': typeof AuthenticatedSelectRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/play/$mediaFileId': typeof AuthenticatedPlayMediaFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/setup' | '/link' | '/select' | '/play/$mediaFileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/setup' | '/link' | '/select' | '/' | '/play/$mediaFileId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/link'
    | '/_authenticated/select'
    | '/_authenticated/'
    | '/_authenticated/play/$mediaFileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/select': {
      id: '/_authenticated/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof AuthenticatedSelectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/link': {
      id: '/_authenticated/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AuthenticatedLinkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/$mediaFileId': {
      id: '/_authenticated/play/$mediaFileId'
      path: '/play/$mediaFileId'
      fullPath: '/play/$mediaFileId'
      preLoaderRoute: typeof AuthenticatedPlayMediaFileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLinkRoute: typeof AuthenticatedLinkRoute
  AuthenticatedSelectRoute: typeof AuthenticatedSelectRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlayMediaFileIdRoute: typeof AuthenticatedPlayMediaFileIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLinkRoute: AuthenticatedLinkRoute,
  AuthenticatedSelectRoute: AuthenticatedSelectRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlayMediaFileIdRoute: AuthenticatedPlayMediaFileIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
