/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SelectRouteImport } from './routes/select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkRouteImport } from './routes/link'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayMediaFileIdRouteImport } from './routes/play.$mediaFileId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMediaFileIdRoute = PlayMediaFileIdRouteImport.update({
  id: '/play/$mediaFileId',
  path: '/play/$mediaFileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/setup': typeof SetupRoute
  '/play/$mediaFileId': typeof PlayMediaFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/setup': typeof SetupRoute
  '/play/$mediaFileId': typeof PlayMediaFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/link': typeof LinkRoute
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/setup': typeof SetupRoute
  '/play/$mediaFileId': typeof PlayMediaFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/link' | '/login' | '/select' | '/setup' | '/play/$mediaFileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/link' | '/login' | '/select' | '/setup' | '/play/$mediaFileId'
  id:
    | '__root__'
    | '/'
    | '/link'
    | '/login'
    | '/select'
    | '/setup'
    | '/play/$mediaFileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinkRoute: typeof LinkRoute
  LoginRoute: typeof LoginRoute
  SelectRoute: typeof SelectRoute
  SetupRoute: typeof SetupRoute
  PlayMediaFileIdRoute: typeof PlayMediaFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mediaFileId': {
      id: '/play/$mediaFileId'
      path: '/play/$mediaFileId'
      fullPath: '/play/$mediaFileId'
      preLoaderRoute: typeof PlayMediaFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkRoute: LinkRoute,
  LoginRoute: LoginRoute,
  SelectRoute: SelectRoute,
  SetupRoute: SetupRoute,
  PlayMediaFileIdRoute: PlayMediaFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
